ECommerce.UI/Models/CategoryListViewModel.cs
using ECommerce.Entities.Models;

namespace ECommerce.UI
{
    public class CategoryListViewModel
    {
        public List<Category> Categories { get; set; }
        public int CurrentCategory { get; set; }
    }
}

ECommerce.UI/Models/ErrorViewModel.cs
namespace ECommerce.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ECommerce.UI/Models/ProductListViewModel.cs
using ECommerce.Entities.Models;

namespace ECommerce.UI.Models
{
    public class ProductListViewModel
    {
        public List<Product>? Products { get; set; }
        public int PageCount { get;  set; }
        public int PageSize { get;  set; }
        public int CurrentPage { get;  set; }
        public int CurrentCategory { get;  set; }
        public bool SortPrice { get;  set; }=false;
        public bool SortOrder { get;  set; }=false;
    }
}

ECommerce.UI/Controllers/HomeController.cs
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ECommerce.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ECommerce.UI/Controllers/ProductController.cs
using ECommerce.Business.Abstract;
using ECommerce.UI.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.UI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IActionResult> Index(int page=1, int category=0,bool sortorder=false, bool sortprice=false)
        {
            int pageSize = 10;
            var items=await _productService.GetAllCategoryAsync(category);



            items = sortprice ? items.OrderByDescending(p => p.UnitPrice).ToList() : items.OrderBy(p => p.UnitPrice).ToList();
            items = sortorder ? items.OrderBy(p => p.ProductName).ToList() : items;

            var products = items.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var model= new ProductListViewModel
            {
                Products = products,
                PageCount =(int)Math.Ceiling(items.Count/(double)pageSize),
                PageSize=pageSize,
                CurrentPage=page,
                CurrentCategory=category,
                SortOrder= sortorder,
                SortPrice= sortprice

            };
            return View (model);
        }
    }
}

ECommerce.UI/ViewComponents/CategoryListViewComponent.cs
using ECommerce.Business.Abstract;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace ECommerce.UI.ViewComponents
{
    public class CategoryListViewComponent: ViewComponent
    {
        private readonly ICategoryService _categoryService;


        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<ViewViewComponentResult> InvokeAsync()
        {
            var categories = await _categoryService.GetAllAsync();
            var param = HttpContext.Request.Query["category"];
            var category=int.TryParse(param, out var categoryId);
            var model = new CategoryListViewModel
            {
                Categories = categories,
                CurrentCategory = category ? categoryId : 0
            };

            return View(model);
        }

    }
}

ECommerce.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ECommerce.UI/Views/Product/Index.cshtml
@model ProductListViewModel





@if(Model.Products==null || Model.Products.Count==0)
{
	<span class="btn-success">No Product exist</span>
}
else
{

	<a class="btn btn-success"
	   href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&sortorder=@(!Model.SortOrder)">
		@(Model.SortOrder ? "Z-A" : "A-Z")
	</a>

	<a class="btn btn-success"
	   href="/product/index?page=@Model.CurrentPage&category=@Model.CurrentCategory&sortprice=@(!Model.SortPrice)">
		@(Model.SortPrice ? "Price: Low to High" : "Price: High to Low")
	</a>
	
	<table class="table">
	<thead>
		<tr>
			<th>Product Name</th>
			<th>Product Price</th>
			<th>Units In Stock</th>
			<th>#</th>
		</tr>
	</thead>

			<tbody>
				@foreach( var item in Model.Products)
				{
					<tr>
						<td>
							@item.ProductName
						</td>
						<td>
							@item.UnitPrice
						</td>
						<td>
							@item.UnitsInStock
						</td>
						<td>
							<a class="btn btn-xs btn-success">Add to Cart</a>
						</td>
					</tr>
				}

			</tbody>
	</table>

	<porduct-list-pager
				current-page="Model.CurrentPage"
				page-count="Model.PageCount"
				page-size="Model.PageSize"
				current-category="Model.CurrentCategory"
				sort-order="Model.SortOrder"
				sort-price="Model.SortPrice"
	></porduct-list-pager>


	
}

ECommerce.UI/Views/Shared/Components/CategoryList/Default.cshtml
@model CategoryListViewModel

@{
	var allCategoryCss = Model.CurrentCategory == 0 ? "list-group-item active" : "list-group-item";
}

<section class="list-group">

	<a href="/product/index?category=0"
	   class="@allCategoryCss" style="cursor:pointer">All Categories</a>

	@foreach (var item in Model.Categories)
	{
		var css = "list-group-item";
		@if (item.CategoryId == Model.CurrentCategory)
		{
			css += " active";
		}
		<a href="/product/index?category=@item.CategoryId"
		   class="@css" style="cursor:pointer">@item.CategoryName</a>
	}

</section>

ECommerce.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerce.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce.UI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        <section class="row">

            <div class="col-md-2">
                @await Component.InvokeAsync("CategoryList")
            </div>

            <div class="col-md-10">
                     <main role="main" class="pb-3">
                        @RenderBody()
                        </main>
            </div>

        </section>

   
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ECommerce.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>